DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS brands;

CREATE TABLE brands (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    version BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    FOREIGN KEY (brand_id) REFERENCES brands(id)
);